services:
 nginx:
  image: nginx:alpine
  container_name: nginx
  ports:
   - "8080:80"
  volumes:
  - ./code:/usr/share/nginx/html
  - ./nginx.conf:/etc/nginx/conf.d/default.conf

 php:
  image: web1-php
  container_name: php1
  volumes:
  - ./code:/usr/share/nginx/html
  
